insert into products_description (product_id, category, product_name, description, is_available) values (1, 'Health', 'Diovan HCT', 'Just a Diovan HCT', true);
insert into products_description (product_id, category, product_name, description, is_available) values (2, 'Health', 'OXYGEN', 'Just a OXYGEN', true);
insert into products_description (product_id, category, product_name, description, is_available) values (3, 'Health', 'Anticavity', 'Just a Anticavity', true);
insert into products_description (product_id, category, product_name, description, is_available) values (4, 'Health', 'HYDRALAZINE HYDROCHLORIDE', 'Just a HYDRALAZINE HYDROCHLORIDE', true);
insert into products_description (product_id, category, product_name, description, is_available) values (5, 'Health', 'Chlordiazepoxide Hydrochloride', 'Just a Chlordiazepoxide Hydrochloride', true);
insert into products_description (product_id, category, product_name, description, is_available) values (6, 'Health', 'APAP', 'Just a APAP', true);
insert into products_description (product_id, category, product_name, description, is_available) values (7, 'Health', 'Ipratropium Bromide', 'Just a Ipratropium Bromide', true);
insert into products_description (product_id, category, product_name, description, is_available) values (8, 'Health', 'CareOne Cold Sore Treatment', 'Just a CareOne Cold Sore Treatment', true);
insert into products_description (product_id, category, product_name, description, is_available) values (9, 'Health', 'FENTANYL CITRATE', 'Just a FENTANYL CITRATE', true);
insert into products_description (product_id, category, product_name, description, is_available) values (10, 'Health', 'Bio Wild Oat', 'Just a Bio Wild Oat', true);
insert into products_description (product_id, category, product_name, description, is_available) values (11, 'Grocery', 'Chips Potato All Dressed - 43g', 'Just a Chips Potato All Dressed - 43g', true);
insert into products_description (product_id, category, product_name, description, is_available) values (12, 'Grocery', 'Nacho Chips', 'Just a Nacho Chips', true);
insert into products_description (product_id, category, product_name, description, is_available) values (13, 'Grocery', 'Fruit Salad Deluxe', 'Just a Fruit Salad Deluxe', true);
insert into products_description (product_id, category, product_name, description, is_available) values (14, 'Grocery', 'Bread Sour Rolls', 'Just a Bread Sour Rolls', true);
insert into products_description (product_id, category, product_name, description, is_available) values (15, 'Grocery', 'Mousse - Mango', 'Just a Mousse - Mango', true);
insert into products_description (product_id, category, product_name, description, is_available) values (16, 'Grocery', 'Sobe - Tropical Energy', 'Just a Sobe - Tropical Energy', true);
insert into products_description (product_id, category, product_name, description, is_available) values (17, 'Grocery', 'Lid - 0090 Clear', 'Just a Lid - 0090 Clear', true);
insert into products_description (product_id, category, product_name, description, is_available) values (18, 'Grocery', 'Turnip - Wax', 'Just a Turnip - Wax', true);
insert into products_description (product_id, category, product_name, description, is_available) values (19, 'Grocery', 'Pie Pecan', 'Just a Pie Pecan', true);
insert into products_description (product_id, category, product_name, description, is_available) values (20, 'Grocery', 'Island Oasis - Pina Colada', 'Just a Island Oasis - Pina Colada', true);
insert into products_description (product_id, category, product_name, description, is_available) values (21, 'Gardening', 'Rio Grande Copperlily', 'Just a Rio Grande Copperlily', true);
insert into products_description (product_id, category, product_name, description, is_available) values (22, 'Gardening', 'Florida Wild Indigo', 'Just a Florida Wild Indigo', true);
insert into products_description (product_id, category, product_name, description, is_available) values (23, 'Gardening', 'Degel''s Wart Lichen', 'Just a Degel''s Wart Lichen', true);
insert into products_description (product_id, category, product_name, description, is_available) values (24, 'Gardening', 'Rusby''s Flatsedge', 'Just a Rusby''s Flatsedge', true);
insert into products_description (product_id, category, product_name, description, is_available) values (25, 'Gardening', 'Jones'' Pitcherplant', 'Just a Jones'' Pitcherplant', true);
insert into products_description (product_id, category, product_name, description, is_available) values (26, 'Gardening', 'Floating Antlerfern', 'Just a Floating Antlerfern', true);
insert into products_description (product_id, category, product_name, description, is_available) values (27, 'Gardening', 'Sierra Stonecrop', 'Just a Sierra Stonecrop', true);
insert into products_description (product_id, category, product_name, description, is_available) values (28, 'Gardening', 'Tapertip Hawksbeard', 'Just a Tapertip Hawksbeard', true);
insert into products_description (product_id, category, product_name, description, is_available) values (29, 'Gardening', 'Summer Grape', 'Just a Summer Grape', true);
insert into products_description (product_id, category, product_name, description, is_available) values (30, 'Gardening', 'Golden Hedgehyssop', 'Just a Golden Hedgehyssop', true);
